from .front_matter import render_front_matter_from_template
from .sections import (
    clear_all_section_bodies,
    clear_page_break_before,
    clone_template_section,
    copy_page_setup,
    copy_template_styles,
    ensure_section_has_terminal_paragraph,
    force_section_start_continuous,
    get_target_section,
    normalize_section_starts_for_flow,
    normalize_document_flow,
    remove_unused_sections,
    resync_all_section_layouts_from_template,
    sync_section_layout_from_template,
)
from .styles import (
    apply_image_profile,
    apply_paragraph_profile,
    apply_run_font,
    fix_behind_text_shapes,
    normalize_reference_item_paragraph,
    set_color_property,
    set_enum_property,
)
from .tables import (
    apply_cell_profile,
    apply_table_borders,
    apply_table_column_widths,
    apply_table_profile,
    apply_table_row_profile,
    clear_table_cell_width_constraints,
    ensure_table_spacing,
    fit_table_within_section_width,
    force_table_fill_width,
    measure_table_width,
    scale_table_cells_to_width,
)
from .text import meaningful_runs, replace_heading_text_with_template_runs, replace_paragraph_text, split_heading_text_parts

__all__ = [
    "apply_cell_profile",
    "apply_image_profile",
    "apply_paragraph_profile",
    "apply_run_font",
    "apply_table_borders",
    "apply_table_column_widths",
    "apply_table_profile",
    "apply_table_row_profile",
    "clear_all_section_bodies",
    "clear_page_break_before",
    "clear_table_cell_width_constraints",
    "clone_template_section",
    "copy_page_setup",
    "copy_template_styles",
    "ensure_section_has_terminal_paragraph",
    "ensure_table_spacing",
    "fit_table_within_section_width",
    "fix_behind_text_shapes",
    "force_section_start_continuous",
    "force_table_fill_width",
    "get_target_section",
    "meaningful_runs",
    "measure_table_width",
    "normalize_reference_item_paragraph",
    "normalize_document_flow",
    "normalize_section_starts_for_flow",
    "remove_unused_sections",
    "render_front_matter_from_template",
    "replace_heading_text_with_template_runs",
    "replace_paragraph_text",
    "resync_all_section_layouts_from_template",
    "scale_table_cells_to_width",
    "set_color_property",
    "set_enum_property",
    "split_heading_text_parts",
    "sync_section_layout_from_template",
]
